### ISSUE TITLE
Implement notifications in conjunction with error handling

### ISSUE THREAD

**Issue by mzdr** [gridonic/grunt#1]
It seems like it’s currently very hard to implement a ([global](http://stackoverflow.com/questions/30601022/global-grunt-task-error-handling)) notification system in conjunction with errors/warnings emitted by tasks. Especially with our Grunt eco system ([`load-grunt-config`](https://github.com/firstandthird/load-grunt-config)) it looks like it’s troublesome to realize.

The best I’ve got so far was [grunt-notify](https://github.com/dylang/grunt-notify) but I don’t know how to (globally) catch errors and fire a corresponding notification. Implementing a custom task as some kind of task runner which runs our tasks doesn’t seem right and enough for us. (See [grunt#1297](https://github.com/gruntjs/grunt/issues/1297))

Also it seems like they are planning to implement internal emitting of events on error/success but it looks like it doesn't have happened yet. ([grunt#1167](https://github.com/gruntjs/grunt/issues/1167), [grunt#1036](https://github.com/gruntjs/grunt/issues/1036)) 

The [docs](https://gruntjs.com/api/grunt.event) also still state that

> *[…] Grunt doesn't yet emit any events, […]*

even though it was supposed to land in v0.5 ([grunt#542](https://github.com/gruntjs/grunt/issues/542)) and there is still no sign of it in v1.0.1?  😕

It would be really cool to have notifications when we run grunt and when it succeeds or fails. On the other hand it looks like Gulp is [a little bit ahead](https://medium.com/@boriscoder/catching-errors-on-gulp-js-4682eee2669f) of Grunt regarding this topic. ¯\\\_(ツ)\_/¯ 

@peschee Do you have any experience on this case and would mind to share it?

**Comment by peschee** [comment]
@mzdr Unfortunately not. However, I also don't see this as a priority. It is indeed unfortunate that we can't attach global error handlers. 

The purpose of this would be to simplify detecting when a task fails I suppose? I guess for now a possible "workaround" is just using whatever your terminal of choice provides in terms of triggers upon stuff that's output to the console. In iterm for example, you can easily detect certain words (e.g. "Done." or "Warning" / "Error" and act upon them (e.g. display global notification, ring the terminal bell, bounce the icon dock etc.) https://www.iterm2.com/documentation-triggers.html
